name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
permissions:
  contents: write
  pull-requests: write
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true
      - name: Run Benchmark
        run: set -o pipefail; go test ./... -benchmem -run=^$ -bench . | tee output.txt
      # NOTE: Benchmarks could change with different CPU types
      - name: Get GitHub Runner System Information
        uses: kenchan0130/actions-system-info@v1.3.1
        id: system-info
      - name: Get main branch SHA
        id: get-main-branch-sha
        run: |
          git fetch origin main
          SHA="$(git rev-parse origin/main)"
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      - name: Get Benchmark Results from main branch
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./cache
          key: ${{ steps.get-main-branch-sha.outputs.sha }}-${{ runner.os }}-${{ steps.system-info.outputs.cpu-model }}-benchmark
      # This will only run if we have Benchmark Results from main branch
      - name: Compare PR Benchmark Results with main branch
        uses: benchmark-action/github-action-benchmark@v1
        if: steps.cache.outputs.cache-hit == 'true'
        with:
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          # Do not save the data (This allows comparing benchmarks)
          save-data-file: false
          fail-on-alert: true
          # Comment on the PR if the branch is not a fork
          comment-on-alert: ${{ github.event.pull_request.head.repo.fork == false }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          alert-threshold: "150%"
      - name: Store benchmark result for main branch
        uses: benchmark-action/github-action-benchmark@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          # Save the data to external file (cache)
          save-data-file: true
          fail-on-alert: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          alert-threshold: "150%"
      - name: Update Benchmark Results cache
        uses: actions/cache/save@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          path: ./cache
          key: ${{ steps.get-main-branch-sha.outputs.sha }}-${{ runner.os }}-${{ steps.system-info.outputs.cpu-model }}-benchmark